{{- /*
Template for OCP ldap password secret.
*/}}
apiVersion: v1
kind: Secret
metadata:
  name: ldap-secret
  namespace: openshift-config
type: Opaque
data:
{{- $wutcluster := .Values.wutcluster -}}
{{- $tls_dir := printf "clusters/%s/ldap/*" $wutcluster }}
{{- $files := .Files.Glob $tls_dir }}
{{- range $path, $_ := $files }}
  bindPassword: {{ tpl ($.Files.Get $path) $|b64enc | trimSuffix "\n"  }}
{{- end }}
