apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: cluster
spec:
  identityProviders:
  - ldap:
      attributes:
        email:
        - mail
        id:
        - dn
        name:
        - cn
        preferredUsername:
        - sAMAccountName
      bindDN: {{ .Values.ldap.bindDN }}
      bindPassword:
        name: ldap-secret
      insecure: true
      url: {{ .Values.ldap.url }}
    mappingMethod: claim
    name: {{ .Values.ldap.name }}
    type: LDAP
  templates:
    providerSelection:
      name: providers-template
