apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cmcc
  namespace: argocd
spec:
  generators:
    - cluster:
        name: cluster
        clusters:
          - in-cluster
          - kind-managed
  template:
    metadata:
      name: demo-configmap
    values: |
      clusters:
        - name: {{ cluster }}
