apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cm-cc
  namespace: argocd
spec:
  generators:
    - cluster:
        name: cluster
        clusters:
          - in-cluster
          - kind-managed
  template:
    metadata:
      name: demo-configmap
    spec:
      poject: default
      destination:
        name: {{ server }}
        namespace: test-cm
      source:
        helm:
          values: |
            wutcluster: {{ name }}
        path: 'demo-cluster/helm/demo-configmap'
        repoURL: 'git@github.com:Tiriyon/demo-deploy-center'
        targetRevision: main
       syncPolicy:
        automated: {}
        syncOptions:
          - CreateNamespace=true
