apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cmcc
  namespace: argocd
spec:
  generators:
  - clusters: {}
  template:
    metadata:
      name: '{{ name }}-d2ops'
    spec:
      project: default
      destination:
        server: '{{ server }}'
        namespace: test-cm
      source:
        helm:
          values: |
            wutcluster: '{{ name }}'
        path: 'demo-clusters/helm/d2ops/'
        repoURL: 'git@github.com:Tiriyon/demo-deploy-center'
        targetRevision: main
      syncPolicy:
       automated: {}
       syncOptions:
         - CreateNamespace=true
