apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cmcc
  namespace: argocd
spec:
  generators:
    - clusters: {}
  template:
    metadata:
      name: demo-configmap
    spec:
      project: default
      destination:
        name: '{{ item.server }}'
        namespace: test-cm
      source:
        helm:
          values: |
            wutcluster: '{{ item.name }}'
        path: 'demo-cluster/helm/demo-configmap'
        repoURL: 'git@github.com:Tiriyon/demo-deploy-center'
        targetRevision: main
       syncPolicy:
        automated: {}
        syncOptions:
          - CreateNamespace=true
