apiVersion: v2
name: placeholder
description: A Helm chart for Kubernetes

type: application

version: 0.1.0


appVersion: "0.1.0"

dependencies: 
  - name: deploy-center
    version: "0.1.0"
    repository: "file://../../../../templates/deploy-center"
