apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-configmap
{{- $wutcluster := .Values.wutcluster -}}
{{- range .Values.clusters }}
{{- if eq .name $wtucluster }}
data:
  test: {{ .datapoint }}
{{- end }}
{{- end }}
