apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: namespaces-appset
  namespace: clusterops
spec:
  generators:
    - list:
        elements:
          - name: main
          - name: demo-ns
          # add more namespaces here
  template:
    metadata:
      # Correct templating: double braces are parsed by ArgoCD
      name: "ns-{{name}}"
    spec:
      project: default
      source:
        repoURL: git@github.com:Tiriyon/demo-deploy-center.git
        targetRevision: main
        path: "gitops/namespaces/{{name}}"
      destination:
        server: https://kubernetes.default.svc
        namespace: clusterops # the Application resource itself lives in gitops
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
