apiVersion: v1
kind: Pod
metadata:
  labels:
    app.kubernetes.io/instance: in-cluster-main-demo-app
    app.kubernetes.io/name: demo-app
  name: in-cluster-main-demo-app-7ccd8bcbf8-f4g88
  namespace: main
spec:
  containers:
  - env:
    - name: test
      value: test
    image: nginx:latest
    imagePullPolicy: IfNotPresent
    name: demo-app
    ports:
    - containerPort: 80
      name: http
      protocol: TCP
    resources: {}
    securityContext: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-8b7vz
      readOnly: true
  enableServiceLinks: true
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  serviceAccount: in-cluster-main-demo-app
  serviceAccountName: in-cluster-main-demo-app
  terminationGracePeriodSeconds: 30
